name: deploy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Upload to Deno Deploy
        uses: enolink/deployctl@v1
        with:
          project: "frontendpro-14"
          entrypoint: "main.ts"
